name: Linter

on:
  pull_request_target:
      branches: [dev, main, 'feature/version-*']
  push:
      branches-ignore: ['renovate/**']
  
permissions:
  contents: write

jobs:
    test-lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                ref: ${{ github.head_ref }}
                fetch-depth: 0
              
            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install --no-scripts

            - name: Lint
              run: pnpm code:lint